version: "3.7"
services:
  db:
    image: postgres:10.9-alpine
    volumes:
      - database_data:/var/lib/postgressql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: kontabilize
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - kontabilize-network

volumes:
  database_data:
    driver: local

networks:
  kontabilize-network:
    